### ISSUE TITLE
Making it simple for people to contribute new data to this repository

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki.github.io#25] opened 2020-03-26 04:41 UTC
Essentially giving direct links of where to code, templates to follow, how to pull requests, etc.

i feel like i should not be allowed to edit this -mat

ming smells bad

**Comment by varughese** [comment] 2020-05-17 01:52
duplicate of #46

**Closed by varughese** 2020-05-17 01:52 UTC
Labels: enhancement
